<?php

$modversion['name'] = _IC_MOD_NAME;
$modversion['version'] = 4.60;
$modversion['description'] = _IC_MOD_DESC;
$modversion['credits'] = _IC_MOD_CREDITS;
$modversion['author'] = 'alban.montaigu@wanadoo.fr';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/iclogo.png';
$modversion['dirname'] = 'icontent';

// Blocks
$modversion['blocks'][1]['file'] = 'b_icontent_shortcuts.php';
$modversion['blocks'][1]['name'] = _IC_B_SHORTCUTS_NAME;
$modversion['blocks'][1]['description'] = _IC_B_SHORTCUTS_DESC;
$modversion['blocks'][1]['show_func'] = 'b_icontent_shortcuts';
$modversion['blocks'][1]['edit_func'] = 'b_icontent_shortcuts_edit';
$modversion['blocks'][1]['options'] = '25';
$modversion['blocks'][1]['template'] = 'b_icontent_shortcuts.html';

$modversion['blocks'][2]['file'] = 'b_icontent_directories.php';
$modversion['blocks'][2]['name'] = _IC_B_DIRECTORIES_NAME;
$modversion['blocks'][2]['description'] = _IC_B_DIRECTORIES_DESC;
$modversion['blocks'][2]['show_func'] = 'b_icontent_directories';
$modversion['blocks'][2]['edit_func'] = 'b_icontent_directories_edit';
$modversion['blocks'][2]['options'] = '25';
$modversion['blocks'][2]['template'] = 'b_icontent_directories.html';

$modversion['blocks'][3]['file'] = 'b_icontent_top.php';
$modversion['blocks'][3]['name'] = _IC_B_TOPDIRECTORIES_NAME;
$modversion['blocks'][3]['description'] = _IC_B_TOPDIRECTORIES_DESC;
$modversion['blocks'][3]['show_func'] = 'b_icontent_topDirectories';
$modversion['blocks'][3]['edit_func'] = 'b_icontent_topDirectories_edit';
$modversion['blocks'][3]['options'] = '25|10';
$modversion['blocks'][3]['template'] = 'b_icontent_top.html';

$modversion['blocks'][4]['file'] = 'b_icontent_top.php';
$modversion['blocks'][4]['name'] = _IC_B_TOPPAGES_NAME;
$modversion['blocks'][4]['description'] = _IC_B_TOPPAGES_DESC;
$modversion['blocks'][4]['show_func'] = 'b_icontent_topPages';
$modversion['blocks'][4]['edit_func'] = 'b_icontent_topPages_edit';
$modversion['blocks'][4]['options'] = '25|10';
$modversion['blocks'][4]['template'] = 'b_icontent_top.html';

$modversion['blocks'][5]['file'] = 'b_icontent_new.php';
$modversion['blocks'][5]['name'] = _IC_B_NEWPAGES_NAME;
$modversion['blocks'][5]['description'] = _IC_B_NEWPAGES_DESC;
$modversion['blocks'][5]['show_func'] = 'b_icontent_newPages';
$modversion['blocks'][5]['edit_func'] = 'b_icontent_newPages_edit';
$modversion['blocks'][5]['options'] = '25|10';
$modversion['blocks'][5]['template'] = 'b_icontent_new.html';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _IC_BESTPAGES;
$modversion['sub'][1]['url'] = 'index.php?op=top10&amp;rate=1';
$modversion['sub'][2]['name'] = _IC_POPULARPAGES;
$modversion['sub'][2]['url'] = 'index.php?op=top10&amp;hits=1';
// Get icontent custom submenus
global $xoopsDB;
$result = $xoopsDB->queryF('SELECT `name`, `page` FROM `' . $xoopsDB->prefix('icontent_shortcuts') . '` WHERE `submenu`=1');
while (list($name, $page) = $xoopsDB->fetchRow($result)) {
    $modversion['sub'][] = ['name' => $name, 'url' => 'index.php?page=' . $page];
}

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Templates
$modversion['templates'][1]['file'] = 'icontent_explorer.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'icontent_index.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'icontent_page.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'icontent_message.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'icontent_shortcuts.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'icontent_summary.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'icontent_rate.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'icontent_top10.html';
$modversion['templates'][8]['description'] = '';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'icontent_shortcuts';
$modversion['tables'][1] = 'icontent_directories';
$modversion['tables'][2] = 'icontent_pages';
$modversion['tables'][3] = 'icontent_votedata';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'pages_search';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 'page';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'icontent_com_approve';
$modversion['comments']['callback']['update'] = 'icontent_com_update';

// Config Settings (only for modules that need config settings generated automatically)
// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'pageUpdate';
// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_IC_PAGEUPDATE';
// description of this config option displayed under title
$modversion['config'][1]['description'] = '_IC_PAGEUPDATEDESC';
// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'yesno';
// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'int';
// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = 0;
// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
$modversion['config'][1]['options'] = [_IC_NO => 0, _IC_YES => 1];

$modversion['config'][2]['name'] = 'navBar';
$modversion['config'][2]['title'] = '_IC_NAVBAR';
$modversion['config'][2]['description'] = '_IC_NAVBARDESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;
$modversion['config'][2]['options'] = [_IC_NO => 0, _IC_YES => 1];

$modversion['config'][3]['name'] = 'shortcutsOnPages';
$modversion['config'][3]['title'] = '_IC_SHORTCUTSONPAGES';
$modversion['config'][3]['description'] = '_IC_SHORTCUTSONPAGESDESC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;
$modversion['config'][3]['options'] = [_IC_NO => 0, _IC_YES => 1];
